# -*- mode: org; coding: utf-8; -*-
#+title: Rider Waite Smith

The images were drawn by artist Pamela Colman Smith, to the instructions of Christian mystic and occultist Arthur Edward Waite, and originally published by the Rider Company in 1910.

While the deck is sometimes known as a simple, user-friendly one, its imagery, especially in the Trumps, is complex and replete with occult symbolism. The subjects of the trumps are based on those of the earliest decks, but have been significantly modified to reflect Waite and Smith's view of Tarot. An important difference from 'Marseille'-style decks is that Smith drew scenes on the numeric cards to depict divinatory meanings; those divinatory meanings derive, in great part, from traditional cartomantic divinatory meanings (Etteilla and others) and from divinatory meanings first espoused by The Hermetic Order of the Golden Dawn, of which both Waite and Smith were members. However, it isn't the first deck to include completely illustrated numeric cards. The first to do so was the 15th-century Sola-Busca deck; however, in this case, the illustrations apparently were not made to facilitate divination.
